### ISSUE TITLE
Block promoted tweets in replies

### ISSUE THREAD

**Issue by kdizzy07** [ryanckulp/twitter_ad_blocker#32]
I guess they found your extension and are now trying to find ways around it.
When I click on images in twitter and see the replies on the right side, promoted tweets appear there.
![twit](https://user-images.githubusercontent.com/35762499/217220552-242b7351-e8f2-4594-8f47-2a154e9f2044.png)

**Comment by ryanckulp** [comment]
thanks for reporting. i haven't seen this yet but when i spot an example on my feed, will patch the tool catch these too.

**Comment by rajavijayasaradhi** [comment]
@ryanckulp If you go to any famous tweet without a thread, you might ad in replies. 

Also, I started thinking about why the ad blocker is unable to remove ads from replies. It should work on page load right? The component is also the same. What are we missing here?

**Comment by rajavijayasaradhi** [comment]
<img width="1495" alt="Screenshot 2023-04-30 at 12 41 50" src="https://user-images.githubusercontent.com/7780883/235351139-3de1181d-694a-4f88-a4eb-fde26f451912.png">

<img width="1495" alt="Screenshot 2023-04-30 at 12 45 23" src="https://user-images.githubusercontent.com/7780883/235351221-67235d28-1ca7-4e55-80ac-0deb5f2e737b.png">

The best way to replicate this issue is to open any famous tweet with an image. Eg, in the above image, I've opened this tweet, https://twitter.com/Rainmaker1973/status/1652574448401129472/photo/1

**Comment by ryanckulp** [comment]
thanks for the more detailed example! 

managed to reproduce this issue and am working on a fix. TLDR the existing "scroll" event listener doesn't fire when you scroll within the sidebar, because the sidebar isn't technically scrollable.

forthcoming patch will listen for the sidebar to pop out, 'make' it scrollable, then remove ads as if it were the main timeline.

**Comment by ryanckulp** [comment]
handled by https://github.com/ryanckulp/twitter_ad_blocker/commit/e7d25da33cb03a43d2408aa1533d86e18f9df844, thanks again @rajavijayasaradhi !
